name: 'Release master'

on:
  push:
    branches:
      - master

concurrency:
  group: release-master
  cancel-in-progress: true

jobs:
  release-and-deploy-master:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Read java.version from workflow.properties"
        id: java_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: '.github/workflows/workflow.properties'
          property: 'java.version'

      - name: "Read sonar.project.key from workflow.properties"
        id: sonar_project_key
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ".github/workflows/workflow.properties"
          property: "sonar.project.key"

      - name: "Read team from workflow.properties"
        id: team
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ".github/workflows/workflow.properties"
          property: "team"

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          java-version: "${{ steps.java_version.outputs.value }}"
          distribution: "temurin"

      - name: "Install xmlstarlet"
        run: sudo apt-get install xmlstarlet

      - name: "Setup github config"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"

      - name: 'Install package required in changelog.config.js'
        run: |
          npm i conventional-changelog-conventionalcommits

      - name: "Generate changelog"
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          presets: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-on-empty: true
          tag-prefix: "v"
          output-file: false
          skip-version-file: true
          skip-commit: true
          config-file-path: '.github/workflows/changelog.config.js'

      - name: "Generate Jira links for the changelog"
        id: changelog_with_jira_links
        env:
          CHANGELOG: ${{ steps.changelog.outputs.clean_changelog }}
        run: |
          if [ -z "${{ env.CHANGELOG }}" ]; then
            output=""
            echo "::set-output name=text::$output"
          else
            output=$(node .github/workflows/generate-jira-links.js)
            output="${output//'%'/'%25'}"
            output="${output//$'\n'/'%0A'}"
            output="${output//$'\r'/'%0D'}"
            echo "::set-output name=text::$output"
          fi

      - name: "Delete created tag from changelog"
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git push --delete origin v${{ steps.changelog.outputs.version }}
          git tag -d v${{ steps.changelog.outputs.version }}

      - name: "Bump version and push tag"
        # Reads the current version from pom.xml and sets the new version in all pom.xml files (including those in subdirectories)
        # Notes:
        # - {,**/}pom.xml expands to both pom.xml and **/pom.xml
        # - **/pom.xml expands to pom.xml files in subdirectories and will remain the same when no such files exist
        # - ${POM_FILES#**/pom.xml#} replaces the first occurrence of **/pom.xml by an empty string, if it exists
        # - ${POM_FILES%%*( )} removes trailing whitespace
        # - ${POM_FILES// /,} replaces all space characters by commas
        run: |
          if [[ "$(echo **/pom.xml)" == "**/pom.xml" ]]; then
            npx dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml
          else
            export POM_FILES="$(echo {,**/}pom.xml)" \
            && export POM_FILES="${POM_FILES%%*( )}" \
            && export BUMP_FILES="${POM_FILES// / --bumpFiles }" \
            && npx dwmkerr/standard-version --packageFiles pom.xml --bumpFiles $BUMP_FILES
          fi

      - name: "Env variable: PROJECT_VERSION"
        run: echo "PROJECT_VERSION=$(xmlstarlet sel -N my=http://maven.apache.org/POM/4.0.0 -t -m my:project -v my:version pom.xml)" >> $GITHUB_ENV

      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: "Create Github Release"
        uses: softprops/action-gh-release@59c3b4891632ff9a897f99a91d7bc557467a3a22
        with:
          body: ${{ steps.changelog_with_jira_links.outputs.text }}
          tag_name: v${{ env.PROJECT_VERSION }}
          name: v${{ env.PROJECT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Restore Maven cache"
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: "Copy settings.xml"
        uses: CleverShuttle/gh-composite-actions/actions/maven-settings@v1.6.3

      - name: "Build with Maven"
        env:
          USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: mvn clean install

      - name: "Deploy to Artifactory"
        continue-on-error: true
        env:
          USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: mvn -DskipDockerBuild -DskipForbiddenApisCheck -Dmaven.main.skip -DskipTests -DskipIntegrationTests -DskipUnitTests -DskipDependencyCheck deploy

      - name: "Sonar: run analysis for master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=${{ steps.sonar_project_key.outputs.value }}
          -Dsonar.scm.provider=git
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.language=java
          -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
          -Dsonar.dependencyCheck.htmlReportPath=target/site/dependency-check-report.html
          -Dsonar.branch.name=${GITHUB_REF:11}

      - name: "Save Maven cache"
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

      - name: "Format changelog for slack"
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        id: changelog_format
        uses: lovetoknow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ steps.changelog_with_jira_links.outputs.text }}

      - name: "Generate changelog title"
        id: changelog_title
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          output="*Changelog*"
          echo "::set-output name=text::$output"

      - name: "Notification: Success"
        if: ${{ success() && github.event.sender.login != 'renovate[bot]' }}
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{secrets.SLACK_BOT_TOKEN_OMG_BACKEND}}
          secret: ${{secrets.SLACK_BOT_SIGNING_SECRET_OMG_BACKEND}}
          channel: ${{secrets.PRODUCTION_DEPLOYMENTS_SLACK_CHANNEL_ID}}
          message: |
            :white_check_mark: Component <${{ env.REPO_BASE_URL }}|${{ github.event.repository.name }}> ( version `${{ env.PROJECT_VERSION }}` ) was successfully deployed to `PRODUCTION` – <${{ env.REPO_BASE_URL }}/actions/runs/${{ github.run_id }}|Details>

            ${{ steps.changelog_title.outputs.text }}

            ${{ steps.changelog_format.outputs.text }}

      - name: "Notification: Failure"
        if: ${{ failure() }}
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{secrets.SLACK_BOT_TOKEN_OMG_BACKEND}}
          secret: ${{secrets.SLACK_BOT_SIGNING_SECRET_OMG_BACKEND}}
          channel: ${{secrets.PRODUCTION_DEPLOYMENTS_SLACK_CHANNEL_ID}}
          message: |
            :x: ${{ env.DEPLOYED_ENTITY }} <${{ env.REPO_BASE_URL }}|${{ github.event.repository.name }}> ( version `${{ env.PROJECT_VERSION }}` ) failed to be deployed to `PRODUCTION` – <${{ env.REPO_BASE_URL }}/actions/runs/${{ github.run_id }}|Details>
